name: Release new version
on:
  - push
jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build sun-api Docker image
        run: |
          docker build \
            -t ghcr.io/jimmysawczuk/sun-api:latest .
      - name: Push sun-api Docker image
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo $GH_PAT | docker login ghcr.io -u jimmysawczuk --password-stdin
          docker push ghcr.io/jimmysawczuk/sun-api:latest
